### ISSUE TITLE
关于程序中的参数

### ISSUE THREAD

**Issue by vegetableMans** [rimelink-lorawan/java-app-sdk#1]
只需要改ip地址 和 appid就行了吗 
我的显示无权连接

**Comment by rimelink-lorawan** [comment]
mqtt 主题是可以有权限控制的，这个 sdk 是假定了 mqtt 的授权是按应用来的（appid），即mqtt的授权用户名就是 appid。通常，数据相关的主题总有 appid 相关，所以这样做是比较通用的做法，但稍加改造就可以支持将其分开的。

**Comment by vegetableMans** [comment]
那个 我还是不是很懂 您能在解释地清楚一点吗...


------------------ 原始邮件 ------------------
发件人: "rimelink-lorawan"<notifications@github.com>;
发送时间: 2019年10月26日(星期六) 下午5:19
收件人: "rimelink-lorawan/java-app-sdk"<java-app-sdk@noreply.github.com>;
抄送: "-"<1250338084@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rimelink-lorawan/java-app-sdk] 关于程序中的参数 (#1)




mqtt 主题是可以有权限控制的，这个 sdk 是假定了 mqtt 的授权是按应用来的（appid），即mqtt的授权用户名就是 appid。通常，数据相关的主题总有 appid 相关，所以这样做是比较通用的做法，但稍加改造就可以支持将其分开的。

**Comment by rimelink-lorawan** [comment]
在`Client client = new Client("mqtt server", appid, appsecret);`中，appid 是 loraserver 中 application 的 id，每个 device 都是挂在一个具体的 application 下的。

现在假设 mqtt 服务器没有设置鉴权，那么，可以这样实例化：
`Client client = new Client("mqtt server", appid, "");`

现在假设 mqtt 是需要账号密码的，这个账号密码在目前接口的定义下，需要给每个 application 配置一个以 application id 作为用户名的授权账号才能正确使用。

**Comment by vegetableMans** [comment]
谢谢谢谢 我懂了




------------------ 原始邮件 ------------------
发件人: "rimelink-lorawan"<notifications@github.com>;
发送时间: 2019年10月29日(星期二) 下午4:52
收件人: "rimelink-lorawan/java-app-sdk"<java-app-sdk@noreply.github.com>;
抄送: "-"<1250338084@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rimelink-lorawan/java-app-sdk] 关于程序中的参数 (#1)




在Client client = new Client("mqtt server", appid, appsecret);中，appid 是 loraserver 中 application 的 id，每个 device 都是挂在一个具体的 application 下的。
 
现在假设 mqtt 服务器没有设置鉴权，那么，可以这样实例化：
 Client client = new Client("mqtt server", appid, "");
 
现在假设 mqtt 是需要账号密码的，这个账号密码在目前接口的定义下，需要给每个 application 配置一个以 application id 作为用户名的授权账号才能正确使用。
